# Generated by Django 5.2.5 on 2025-08-17 09:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('nin', models.CharField(max_length=30, unique=True)),
                ('recommender_name', models.CharField(max_length=50)),
                ('recommender_nin', models.CharField(max_length=30)),
                ('tel_number', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('farmer_type', models.CharField(choices=[('Starter', 'Starter'), ('Returning', 'Returning')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Feedstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeds_name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('cost_price', models.PositiveIntegerField()),
                ('feeds_type', models.CharField(choices=[('Starter Feeds', 'Starter Feeds'), ('Grower Feeds', 'Grower Feeds'), ('Layer Feeds', 'Layer Feeds'), ('Broiler Feeds', 'Broiler Feeds')], max_length=30)),
                ('feeds_brand', models.CharField(choices=[('Unga Millers (U) Ltd', 'Unga Millers (U) Ltd'), ('Ugachick Poultry Breeders Ltd', 'Ugachick Poultry Breeders Ltd'), ('Kaffiika Animal Feeds', 'Kaffiika Animal Feeds'), ('Biyinzika Poultry International Limited', 'Biyinzika Poultry International Limited')], max_length=50)),
                ('feeds_supplier', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_salesagent', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'farmer_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chick_type', models.CharField(choices=[('Broiler', 'Broiler'), ('Layer', 'Layer')], max_length=20)),
                ('chick_breed', models.CharField(choices=[('Local', 'Local'), ('Exotic', 'Exotic')], max_length=15)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('feeds_needed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('feeds_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('chicks_period', models.PositiveIntegerField()),
                ('delivered', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('batch_name', models.CharField(max_length=255, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('chick_type', models.CharField(choices=[('Broiler', 'Broiler'), ('Layer', 'Layer')], max_length=20)),
                ('chick_breed', models.CharField(choices=[('Local', 'Local'), ('Exotic', 'Exotic')], max_length=20)),
                ('price', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('chicks_age', models.PositiveIntegerField()),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
